// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.OutputAdapters.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.OutputAdapters.DataAccess.Migrations
{
    [DbContext(typeof(GeoClubBotDbContext))]
    partial class GeoClubBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.AiConversationTurn", b =>
                {
                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AuthorDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<decimal>("ConversationId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("ParentDiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("TurnId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DiscordMessageId")
                        .IsUnique();

                    b.HasIndex("AuthorDiscordUserId", "CreatedAtUtc");

                    b.ToTable("AiConversationTurns");
                });

            modelBuilder.Entity("Entities.AiDailyBudget", b =>
                {
                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.HasKey("DateUtc");

                    b.ToTable("AiDailyBudgets");
                });

            modelBuilder.Entity("Entities.Club", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LatestActivityCheckTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ClubId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Entities.ClubChallengeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolePriority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LatestClubChallengeLinks");
                });

            modelBuilder.Entity("Entities.ClubMember", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PrivateTextChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("Entities.ClubMemberExcuse", b =>
                {
                    b.Property<Guid>("ExcuseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("ExcuseId");

                    b.HasIndex("To");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMemberExcuses");
                });

            modelBuilder.Entity("Entities.ClubMemberHistoryEntry", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Timestamp", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ClubId", "UserId", "Timestamp");

                    b.ToTable("ClubMemberHistoryEntries");
                });

            modelBuilder.Entity("Entities.ClubMemberStrike", b =>
                {
                    b.Property<Guid>("StrikeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("StrikeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMemberStrikes");
                });

            modelBuilder.Entity("Entities.DailyMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MapName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MapSlug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("integer");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TargetProgress")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAtUtc");

                    b.HasIndex("MissionId");

                    b.ToTable("DailyMissions");
                });

            modelBuilder.Entity("Entities.DailyMissionMemberCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyChallengeCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Date", "UserId")
                        .IsUnique();

                    b.ToTable("DailyMissionMemberCompletions");
                });

            modelBuilder.Entity("Entities.DailyMissionReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly?>("LastSentDateUtc")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ReminderTimeUtc")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("ReminderTimeUtc", "LastSentDateUtc");

                    b.ToTable("DailyMissionReminders");
                });

            modelBuilder.Entity("Entities.GeoGuessrAccountLinkingRequest", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GeoGuessrUserId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("OneTimePassword")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.HasKey("DiscordUserId", "GeoGuessrUserId");

                    b.ToTable("GeoGuessrAccountLinkingRequests");
                });

            modelBuilder.Entity("Entities.GeoGuessrUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal?>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UserId");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.HasIndex("Nickname");

                    b.ToTable("GeoGuessrUsers");
                });

            modelBuilder.Entity("Entities.KnowledgeSource", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Continent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ImagesDeferred")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastIngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RemovedFromSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("SourceId");

                    b.HasIndex("SourceType", "NaturalKey")
                        .IsUnique();

                    b.HasIndex("Status", "LastAttemptedAtUtc");

                    b.ToTable("KnowledgeSources");
                });

            modelBuilder.Entity("Entities.ClubMember", b =>
                {
                    b.HasOne("Entities.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.GeoGuessrUser", "User")
                        .WithOne()
                        .HasForeignKey("Entities.ClubMember", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.ClubMemberExcuse", b =>
                {
                    b.HasOne("Entities.ClubMember", "ClubMember")
                        .WithMany("Excuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubMember");
                });

            modelBuilder.Entity("Entities.ClubMemberHistoryEntry", b =>
                {
                    b.HasOne("Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.ClubMember", "ClubMember")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ClubMember");
                });

            modelBuilder.Entity("Entities.ClubMemberStrike", b =>
                {
                    b.HasOne("Entities.ClubMember", "ClubMember")
                        .WithMany("Strikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubMember");
                });

            modelBuilder.Entity("Entities.ClubMember", b =>
                {
                    b.Navigation("Excuses");

                    b.Navigation("History");

                    b.Navigation("Strikes");
                });
#pragma warning restore 612, 618
        }
    }
}
